spring.datasource.url=jdbc:postgresql://localhost:5433/knowledgeos
spring.datasource.username=postgres
spring.datasource.password=password
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
crawler.max-pages=500